language: python
os:
- linux
dist: trusty
sudo: required
python:
- '3.5'
- '3.6'
script:
- python setup.py install
- get_n_genomes -h
- plentyofbugs --version
- nosetests plentyofbugs/ -v

stages:
  allow_failures:
  - deploy
deploy:
  provider: pypi
  user: NickWaters
  password:
    secure: Xe4iWZalFASjGTEuK3tX/R6B7n8qrThb6kqFESwZtdxdVv1KL/XzHySpwKYhVnPnNTgBtXNHdtpE+sWmClUN+R+HEbW1Sdnd04vXQd8z/nuTrYqgLqOwshnWOrBoPO68begXnOZndkNylPUZdh/q6dVbfz6cL53AFwzpwRFpMuXeNUo1dErm8fqMlYmxC3npZVtl8pnB+5EeKjilzhgSftPvNqGYTS1Se6CCFUA4Z/mquHu+xLW5TrYkKpbQsRFJrYQtknjftF/mU5stSkTq3uQZRdyrnpK5a+vUJeA6teI5b7DllhkZbjtVfBxt6HMWYEwCuy0C8/O5W1MiSRjns6advKpuHiRII08XI43va1PR4TQh3DEoXYydgjZ4LcgZ8MEhDJoxK9Hfiy1FvoDUMXglDVZ1ogTlR7c/MTkP3+WAX/sOMoSTWLmndMhjx3SrdV5Tx9/luao9/K6wTryhaSrvzXJSQkCrxwbxNLFSmQhY0ZeAnBE7koHiPruczTIKUlcGx/EyZcgQ4w3/QneXsxXEct9oiJL9QeCzZe1DefG7u5X2ATHAXBT14HsAaHg41p3K60qLfU+hUWXRwi36VgErPeDzU4omGt3zrJtBc6QNoYyr/YERkcjtRFZATRdvPtbRoKmYDzSsMZlUKvqjU5mK/PJmoStR3SxnKsQ4Vo0=
